version: '3.1'

services:
  db:
    container_name: agenda
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agendaDB
    ports:
      - "5454:5432"

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  #app:
  #  build: .
  #  container_name: app
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - db
  #  volumes:
  #    - ./src:/app/src
  #  command: npm start
  #  networks:
  #    - mynetwork
    
volumes:
  postgres_data: