version: '3.1'

services:
  db:
    container_name: agenda
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5454:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

volumes:
  postgres_data: